"""Tree Search Distilling Agent for AReaL integration.

Extends OnPolicyDistillAgent with a student-only position rewards path
that builds PositionRewardInfo from student top-k logprobs when no
teacher model is configured. This ensures multi-candidate logprobs are
still gathered during training for logging and analysis.
"""

from __future__ import annotations

import hashlib
from typing import Any

from customized_areal.on_policy_distill.core.agent import OnPolicyDistillAgent
from customized_areal.on_policy_distill.core.teacher_client import (
    TeacherConfig,
)
from customized_areal.on_policy_distill.proxy.cache import PositionRewardInfo

from areal.utils import logging

logger = logging.getLogger("TreeDistillAgent")


def _build_student_only_position_rewards(
    student_output_ids: list[int],
    student_top_k_logprobs: list[list[tuple[int, float]]],
    top_k: int = 10,
) -> list[PositionRewardInfo]:
    """Build PositionRewardInfo from student top-k logprobs without a teacher.

    Creates position-level reward data for logging and multi-candidate
    logprob gathering. Rewards are all zeros (no teacher signal), so the
    distillation loss contributes nothing while student logprobs are still
    captured.

    Parameters
    ----------
    student_output_ids : list[int]
        Token IDs actually generated by the student model.
    student_top_k_logprobs : list[list[tuple[int, float]]]
        For each output position, a list of (token_id, logprob) tuples.
    top_k : int
        Maximum number of candidate tokens per position. Defaults to 10.

    Returns
    -------
    list[PositionRewardInfo]
        One PositionRewardInfo per output position, with zero rewards
        and student logprobs for each candidate.
    """
    if not student_output_ids or not student_top_k_logprobs:
        return []

    results: list[PositionRewardInfo] = []
    for i, pos_logprobs in enumerate(student_top_k_logprobs):
        truncated = pos_logprobs[:top_k]
        candidate_token_ids = [tid for tid, _ in truncated]
        student_lps = [lp for _, lp in truncated]
        rewards = [0.0] * len(candidate_token_ids)

        chosen_tid = student_output_ids[i]
        try:
            chosen_index = candidate_token_ids.index(chosen_tid)
        except ValueError:
            chosen_index = 0

        results.append(
            PositionRewardInfo(
                position=i,
                candidates=[str(tid) for tid in candidate_token_ids],
                candidate_token_ids=candidate_token_ids,
                logprobs=student_lps,
                rewards=rewards,
                chosen_index=chosen_index,
            )
        )

    logger.debug("Built student-only position rewards: %d positions", len(results))
    return results


class TreeDistillAgent(OnPolicyDistillAgent):
    """On-policy distillation agent that also saves student logprobs without a teacher.

    When a teacher model is configured, behaves identically to
    OnPolicyDistillAgent (computing student - teacher rewards).

    When no teacher is configured, builds PositionRewardInfo from the
    student's own top-k logprobs with zero rewards, ensuring
    multi-candidate logprobs are still gathered during training for
    logging and analysis.
    """

    def __init__(
        self,
        agent_id: str | None = None,
        user_id: str | None = None,
        model_name: str | None = None,
        teacher_config: TeacherConfig | None = None,
        student_top_k: int = 10,
        **kwargs,
    ):
        """Initialize TreeDistillAgent.

        Args:
            agent_id: Optional agent ID.
            user_id: Optional user ID for authentication.
            model_name: Optional model name for LLM calls.
            teacher_config: Optional TeacherConfig. If None, student-only
                position rewards are built with zero distillation rewards.
            student_top_k: Number of top candidate tokens per position
                for student-only logprob gathering. Defaults to 10.
            **kwargs: Additional keyword arguments passed to OnPolicyDistillAgent.
        """
        super().__init__(
            agent_id=agent_id,
            user_id=user_id,
            model_name=model_name,
            teacher_config=teacher_config,
            **kwargs,
        )
        self.student_top_k = student_top_k

    async def run(
        self,
        data: dict[str, Any],
        **extra_kwargs,
    ) -> float | dict[str, dict[str, Any]]:
        """Execute a single agent run, returning reward with position-level data.

        When a teacher is configured, computes student - teacher logprob
        rewards as in OnPolicyDistillAgent. When no teacher is configured,
        builds PositionRewardInfo with student logprobs and zero rewards
        so that multi-candidate logprobs are still gathered during training.
        """
        # Run the parent agent first to get the base reward and teacher
        # position rewards (if teacher is configured)
        result = await super().run(data, **extra_kwargs)

        # If teacher was configured and produced position rewards, return as-is
        if isinstance(result, dict) and any(
            "position_rewards" in v for v in result.values() if isinstance(v, dict)
        ):
            return result

        # If no teacher was configured, try to build student-only position rewards
        if self.teacher_client is None:
            proxy_client = extra_kwargs.get("proxy_client")
            if proxy_client is not None:
                try:
                    interaction = await proxy_client.get_last_interaction()
                    if (
                        interaction
                        and hasattr(interaction, "model_response")
                        and interaction.model_response is not None
                    ):
                        student_output_ids = interaction.model_response.output_tokens
                        student_top_k_logprobs = getattr(
                            interaction.model_response, "output_top_logprobs", None
                        )
                        if student_top_k_logprobs is not None:
                            position_rewards = _build_student_only_position_rewards(
                                student_output_ids=student_output_ids,
                                student_top_k_logprobs=student_top_k_logprobs,
                                top_k=self.student_top_k,
                            )
                            if position_rewards:
                                # Compute completion_id the same way as parent
                                completion_messages = data.get("messages", [])
                                completion_id = hashlib.md5(
                                    str(completion_messages).encode()
                                ).hexdigest()[:16]
                                # result is a float (scalar reward) from parent
                                scalar_reward = (
                                    result if isinstance(result, (int, float)) else 0.0
                                )
                                logger.info(
                                    "Built student-only position rewards: %d positions, "
                                    "scalar_reward=%.4f",
                                    len(position_rewards),
                                    scalar_reward,
                                )
                                return {
                                    completion_id: {
                                        "position_rewards": position_rewards,
                                        "scalar_reward": scalar_reward,
                                    }
                                }
                except Exception as e:
                    logger.warning(
                        "Failed to build student-only position rewards: %s",
                        e,
                        exc_info=True,
                    )

        return result
