from __future__ import annotations

import uuid

from starlette.requests import Request
from starlette.responses import JSONResponse


def aerl_error_response(
    request: Request,
    *,
    code: str,
    message: str,
    status_code: int = 400,
) -> JSONResponse:
    """JSON body for failures generated by AERL (spec §3)."""
    rid = getattr(request.state, "request_id", None) or str(uuid.uuid4())
    return JSONResponse(
        {"error": {"code": code, "message": message, "request_id": rid}},
        status_code=status_code,
    )
